### PR TITLE
Update Nuget packages as much a possible for .Net core 3.1

### PR DESCRIPTION
**Pull request by zur003**
Working on #7139

### CODE REVIEW

**Comment by zur003** [comment]
@hol430 - Do you have any clues as to why the build is failing? The messages indicate a failure to load Microsoft.CodeAnalysis version 3.11.0, but specifying that version in the package lists made no difference. Does this have something to do with the Jenkins build environment?

**Comment by hol430** [comment]
Hi @zur003 - I'm not sure exactly what's causing the problem, but when I built your branch locally, I encountered a different error:

```
MSBuild version 17.4.0+18d5aef85 for .NET
  Determining projects to restore...
  Restored /home/drew/code/ApsimX/APSIM.Shared/APSIM.Shared.csproj (in 49.23 sec).
  Restored /home/drew/code/ApsimX/Models/Models.csproj (in 52.97 sec).
  Restored /home/drew/code/ApsimX/APSIM.Server/APSIM.Server.csproj (in 53.38 sec).
  Restored /home/drew/code/ApsimX/APSIM.Cli/APSIM.Cli.csproj (in 1.04 min).
  Restored /home/drew/code/ApsimX/APSIM.Interop/APSIM.Interop.csproj (in 1.04 min).
  Restored /home/drew/code/ApsimX/APSIM.Documentation/APSIM.Documentation.csproj (in 1.04 min).
  Restored /home/drew/code/ApsimX/ApsimNG/ApsimNG.csproj (in 1.09 min).
  Restored /home/drew/code/ApsimX/Tests/UnitTests/UnitTests.csproj (in 1.09 min).
  APSIM.Shared -> /home/drew/code/ApsimX/bin/Debug/netcoreapp3.1/APSIM.Shared.dll
  Models -> /home/drew/code/ApsimX/bin/Debug/netcoreapp3.1/Models.dll
  APSIM.Interop -> /home/drew/code/ApsimX/bin/Debug/netcoreapp3.1/APSIM.Interop.dll
  APSIM.Server -> /home/drew/code/ApsimX/bin/Debug/netcoreapp3.1/apsim-server.dll
  APSIM.Documentation -> /home/drew/code/ApsimX/bin/Debug/netcoreapp3.1/APSIM.Documentation.dll
  APSIM.Cli -> /home/drew/code/ApsimX/bin/Debug/netcoreapp3.1/apsim.dll
/home/drew/code/ApsimX/ApsimNG/Presenters/IntellisensePresenter.cs(313,53): error CS1061: 'CompletionList' does not contain a definition for 'ItemsList' and no accessible extension method 'ItemsList' accepting a first argument of type 'CompletionList' could be found (are you missing a using directive or an assembly reference?) [/home/drew/code/ApsimX/ApsimNG/ApsimNG.csproj::TargetFramework=netcoreapp3.1]
/home/drew/code/ApsimX/ApsimNG/Intellisense/CodeCompletionService.cs(138,71): error CS7036: There is no argument given that corresponds to the required parameter 'workspace' of 'Recommender.GetRecommendedSymbolsAtPositionAsync(SemanticModel, int, Workspace, OptionSet?, CancellationToken)' [/home/drew/code/ApsimX/ApsimNG/ApsimNG.csproj::TargetFramework=netcoreapp3.1]
/home/drew/code/ApsimX/ApsimNG/Intellisense/CodeCompletionService.cs(141,68): error CS1061: 'CompletionList' does not contain a definition for 'ItemsList' and no accessible extension method 'ItemsList' accepting a first argument of type 'CompletionList' could be found (are you missing a using directive or an assembly reference?) [/home/drew/code/ApsimX/ApsimNG/ApsimNG.csproj::TargetFramework=netcoreapp3.1]

Build FAILED.

/home/drew/code/ApsimX/ApsimNG/Presenters/IntellisensePresenter.cs(313,53): error CS1061: 'CompletionList' does not contain a definition for 'ItemsList' and no accessible extension method 'ItemsList' accepting a first argument of type 'CompletionList' could be found (are you missing a using directive or an assembly reference?) [/home/drew/code/ApsimX/ApsimNG/ApsimNG.csproj::TargetFramework=netcoreapp3.1]
/home/drew/code/ApsimX/ApsimNG/Intellisense/CodeCompletionService.cs(138,71): error CS7036: There is no argument given that corresponds to the required parameter 'workspace' of 'Recommender.GetRecommendedSymbolsAtPositionAsync(SemanticModel, int, Workspace, OptionSet?, CancellationToken)' [/home/drew/code/ApsimX/ApsimNG/ApsimNG.csproj::TargetFramework=netcoreapp3.1]
/home/drew/code/ApsimX/ApsimNG/Intellisense/CodeCompletionService.cs(141,68): error CS1061: 'CompletionList' does not contain a definition for 'ItemsList' and no accessible extension method 'ItemsList' accepting a first argument of type 'CompletionList' could be found (are you missing a using directive or an assembly reference?) [/home/drew/code/ApsimX/ApsimNG/ApsimNG.csproj::TargetFramework=netcoreapp3.1]
    0 Warning(s)
    3 Error(s)
```

I only have the .net 7 sdk installed - no others:

```
~ $ dotnet --list-sdks
7.0.100 [/usr/share/dotnet/sdk]
```

I then installed the .net core 3.1 sdk to a non-standard path and changed my `DOTNET_ROOT` and `PATH` variables such that only the v3.1 sdk was available in my shell and rebuilt apsim, and I ran into the same error that we're seeing on Jenkins. An easier way to reproduce that would be to build apsim in a docker that has only the 3.1 sdk installed - just use the `apsiminitiative/apsimng-build:latest` image (or a .net core 3.1 sdk image if there is one).

As for why the package doesn't work, I'm not sure. When I build with the 3.1 sdk, I can see that the Microsoft.CodeAnalysis package has been restored successfully, and can see its assembly in the bin directory. Perhaps there is some problem with this version of the package, or perhaps it's a problem with the older version of the sdk. If it's the latter, someone with push access to the apsiminitiative docker repo may need to update the apsimng-build docker image.

**Comment by zur003** [comment]
Thanks for testing, @hol430 . The code completion errors were my fault. In my initial PR, I had modified the code slightly to allow it to work correctly with version 4.4 of the CodeAnalysis packages. A later modification reverted CodeAnalysis back to 3.11, but I foolishly forgot to revert the changes made to the code completion units.

I'll see what I can do with version 3.1, but is there any prospect of the build image moving to a more current sdk?

**Comment by zur003** [comment]
@hol430 - This may be a known Roslyn problem. See [https://github.com/dotnet/roslyn/issues/54625](https://github.com/dotnet/roslyn/issues/54625). I think my "reversion" didn't go back far enough. I shall try again.

**Comment by hol430** [comment]
Agreed, updating the sdk makes sense. Once APSIMInitiative/APSIM.Docker#2 is merged, and the image on dockerhub is updated, you may be able to re-do your changes to the CodeAnalysis packages.

**Comment by hol353** [comment]
I've merged https://github.com/APSIMInitiative/APSIM.Docker/pull/2.

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
Ok an update. I have got the build working again - sort of. Since we've changed the .NET version to 7 we are now getting fails like this:
```
System.Exception: Error from R:
Script path: '/tmp/fdc73a03-c879-4c40-ab1f-9ab08d64a7e9-getPackage.R'
StdErr:
Warning in install.packages(pkg, repos = "https://cran.csiro.au/", lib = pkgpath,  :
  'lib = "ApsimInitiative/ApsimX/rpackages"' is not writable
Error in install.packages(pkg, repos = "https://cran.csiro.au/", lib = pkgpath,  : 
  unable to install packages
Calls: getPackage -> install.packages
In addition: Warning message:
In dir.create(pkgpath) :
  cannot create dir 'ApsimInitiative/ApsimX/rpackages', reason 'No such file or directory'
Execution halted

StdOut:

Script contents:
#' Loads a package, installing it if necessary.
#'
#' @param pkg Name of the package to be installed/loaded.
#' @param pkgpath Path where package is to be installed.
#' @return Nothing.
getPackage <- function(pkg, pkgpath) {
    if (!pkg %in% rownames(installed.packages())) {
        if (!dir.exists(pkgpath)) {
            dir.create(pkgpath)
        }
        install.packages(pkg, repos = "https://cran.csiro.au/", lib = pkgpath, dependencies = TRUE)
	} else {
		print(paste('Package', pkg, 'is already installed.'))
	}
}

args = commandArgs(TRUE)
getPackage(args[1], args[2])



   at Models.Utilities.R.Run(String fileName, Boolean throwOnError, String[] arguments) in /tmp/ApsimX/Models/Utilities/R.cs:line 194
   at Models.Utilities.R.InstallPackage(String package) in /tmp/ApsimX/Models/Utilities/R.cs:line 265
   at Models.Utilities.R.InstallPackages(String[] packages) in /tmp/ApsimX/Models/Utilities/R.cs:line 307
   at Models.Optimisation.CroptimizR.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Optimisation/CroptimizR.cs:line 497
   at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 225
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 189
CroptimizR has finished. Elapsed time was 3.7 seconds.
```

After some looking at the code I think the problem is the above path 'ApsimInitiative/ApsimX/rpackages' that is being passed to R from our C# code. We calculate this path in R.cs line 59:
```c#
public static string PackagesDirectory { get; } = Path.Combine(
                                    Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
                                    "ApsimInitiative",
                                    "ApsimX",
                                    "rpackages").Replace("\\", "/");
```

I suspect that ```Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)``` is returning a blank now when it was returning something different in the older .NET. I've run out of time today and will look at it again on Friday.

**Comment by zur003** [comment]
The Microsoft docs for `GetFolderPath` states that it returns:

> The path to the specified system special folder, if that folder physically exists on your computer; otherwise, an empty string ("").
A folder will not physically exist if the operating system did not create it, the existing folder was deleted, or the folder is a virtual directory, such as My Computer, which does not correspond to a physical path.

You can add a second argument of `Environment.SpecialFolderOptions.Create` in the call to `GetFolderPath` that will create the folder if it doesn't exist. That may be worth a try.

I would apologise for triggering all this confusion, but it appears to be something that would have to be dealt with sooner or later.

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
You know the thing about the definition of insanity being doing the same thing over and over and expecting a different result? Well, I've been doing the same thing over and over, expecting the same result, and getting a slightly different result each time, and it's driving me insane.

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
Is rtools installed on the Docker image? It's apparently needed to install CroptimizR.

**Comment by hol430** [comment]
So, I think the problem is the lack of a BayesianTools package on cran at the moment. I'm currently attempting to install from source and will submit a patched dockerfile if that works. Unfortunately building all of the dependencies takes quite a long time...

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
@hol430 I've merged your BayesianTools PR, built the docker R image and pushed to DockerHub and rerun this PR - same error as before. I'll dig a bit deeper...

**Comment by hol430** [comment]
From a quick look, I'd say you only rebuilt the apsimng-r image. apsimng-complete and then apsimng-build will also need to be rebuilt and pushed to dockerhub (as they use apsimng-r as a base layer).

**Comment by hol353** [comment]
Yep I just figured that out as well. I'm rebuilding apsimng-build right now. I'm getting network issues though. Not sure if it is my computer, CSIRO's network this morning or something else. Lots of timeouts with apt-get doing an update. It was ok on Wednesday. Grrr this is harder than it should be.

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
Ok next problem. The apsim release system is failing - see Jenkins log here https://jenkins.apsim.info/job/apsim-release/170/console

```
CSC : warning CS8032: An instance of analyzer Microsoft.Extensions.Logging.Generators.LoggerMessageGenerator cannot be created from C:\Users\ContainerAdministrator\.nuget\packages\microsoft.extensions.logging.abstractions\6.0.0\analyzers\dotnet\roslyn3.11\cs\Microsoft.Extensions.Logging.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Server\APSIM.Server.csproj]
CSC : warning CS8032: An instance of analyzer Microsoft.Extensions.Logging.Generators.LoggerMessageGenerator cannot be created from C:\Users\ContainerAdministrator\.nuget\packages\microsoft.extensions.logging.abstractions\6.0.0\analyzers\dotnet\roslyn4.0\cs\Microsoft.Extensions.Logging.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Server\APSIM.Server.csproj]
CSC : warning CS8032: An instance of analyzer System.Text.Json.SourceGeneration.JsonSourceGenerator cannot be created from C:\Users\ContainerAdministrator\.nuget\packages\system.text.json\6.0.5\analyzers\dotnet\roslyn3.11\cs\System.Text.Json.SourceGeneration.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Server\APSIM.Server.csproj]
CSC : warning CS8032: An instance of analyzer System.Text.Json.SourceGeneration.JsonSourceGenerator cannot be created from C:\Users\ContainerAdministrator\.nuget\packages\system.text.json\6.0.5\analyzers\dotnet\roslyn4.0\cs\System.Text.Json.SourceGeneration.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Server\APSIM.Server.csproj]

  APSIM.Server -> C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\bin\Release\netcoreapp3.1\apsim-server.dll

CSC : error CS8032: An instance of analyzer Microsoft.Extensions.Logging.Generators.LoggerMessageGenerator cannot be created from C:\Users\ContainerAdministrator\.nuget\packages\microsoft.extensions.logging.abstractions\6.0.0\analyzers\dotnet\roslyn3.11\cs\Microsoft.Extensions.Logging.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\ApsimNG\ApsimNG.csproj]
CSC : error CS8032: An instance of analyzer Microsoft.Extensions.Logging.Generators.LoggerMessageGenerator cannot be created from C:\Users\ContainerAdministrator\.nuget\packages\microsoft.extensions.logging.abstractions\6.0.0\analyzers\dotnet\roslyn4.0\cs\Microsoft.Extensions.Logging.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\ApsimNG\ApsimNG.csproj]
CSC : error CS8032: An instance of analyzer System.Text.Json.SourceGeneration.JsonSourceGenerator cannot be created from C:\Users\ContainerAdministrator\.nuget\packages\system.text.json\6.0.5\analyzers\dotnet\roslyn3.11\cs\System.Text.Json.SourceGeneration.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\ApsimNG\ApsimNG.csproj]
CSC : error CS8032: An instance of analyzer System.Text.Json.SourceGeneration.JsonSourceGenerator cannot be created from C:\Users\ContainerAdministrator\.nuget\packages\system.text.json\6.0.5\analyzers\dotnet\roslyn4.0\cs\System.Text.Json.SourceGeneration.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\ApsimNG\ApsimNG.csproj]
Microsoft (R) Build Engine version 16.10.1+2fd48ab73 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
```

I'm guessing this is a consequence of moving from .NET 3.1 to .NET 7

**Comment by hol353** [comment]
Actually, I now get these errors when I compile ApsimNG on my computer (using VS 2019) (after doing a pull). Do we all need to move to VS 2022? Probably should anyway.

**Comment by lie112** [comment]
VS 2022 is great. Plus, you get a true 64-bit interface. APSIM Next Gen works fine in 2022. I've been using it since its release.
I'm looking forward to getting up to a newer version of .Net for coding concepts and styles and also the significant performance benefits in many aspects of the code that come for free.

**Comment by zur003** [comment]
@hol353 - I have no trouble with compiling under VS 2019 on my computer; I think the critical issue is whether the .Net 6.0 (or 7.0) SDK has been installed. That said, moving to VS2022 is probably the best way to go, and will bring in the needed SDK update.

We're only partway there - the build is still targeting .Net 3.1. Changing that to .Net 6 will require changes to the installers, I think. See the comments from @hol430 in issue #7139.

**Comment by hol353** [comment]
I installed .NET 7 and tried VS2019 again - didn't work.
I used VS2022 and it said I needed to install the .NET 3.1 SDK (I would have thought it was already installed) and then it worked. I'll use VS2022. 

It probably means everyone should switch to VS2022 and install .NET 7 SDK. There is still the problem of Jenkins creating releases atm. Probably because .NET 7 is missing. I'll look into it.

**Comment by hol353** [comment]
I've run out of time today so some notes to myself. I have updated the apsimng-windows dockerfile to use .NET 7. I have built the docker image and pushed it to dockerhub. This will hopefully solve the above errors.

The debian installer is showing these errors:
```
usr/share/dotnet/sdk/7.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1124,5): error NETSDK1151: The referenced project '../Models/Models.csproj' is a self-contained executable.  A self-contained executable cannot be referenced by a non self-contained executable.  For more information, see https://aka.ms/netsdk1151 [/tmp/ApsimX/APSIM.Server/APSIM.Server.csproj]
  APSIM.Shared -> /tmp/ApsimX/bin/Release/netcoreapp3.1/linux-x64/APSIM.Shared.dll
  APSIM.Shared -> /tmp/ApsimX/bin/Release/netcoreapp3.1/APSIM.Shared.dll
  APSIM.Shared -> /tmp/ApsimX/bin/Release/netcoreapp3.1/linux-x64/publish/
/usr/share/dotnet/sdk/7.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1124,5): error NETSDK1151: The referenced project '../Models/Models.csproj' is a self-contained executable.  A self-contained executable cannot be referenced by a non self-contained executable.  For more information, see https://aka.ms/netsdk1151 [/tmp/ApsimX/APSIM.Cli/APSIM.Cli.csproj::TargetFramework=netcoreapp3.1]
/usr/share/dotnet/sdk/7.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1124,5): error NETSDK1151: The referenced project '../Models/Models.csproj' is a self-contained executable.  A self-contained executable cannot be referenced by a non self-contained executable.  For more information, see https://aka.ms/netsdk1151 [/tmp/ApsimX/APSIM.Documentation/APSIM.Documentation.csproj]
/usr/share/dotnet/sdk/7.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1124,5): error NETSDK1151: The referenced project '../Models/Models.csproj' is a self-contained executable.  A self-contained executable cannot be referenced by a non self-contained executable.  For more information, see https://aka.ms/netsdk1151 [/tmp/ApsimX/ApsimNG/ApsimNG.csproj::TargetFramework=netcoreapp3.1]
/usr/share/dotnet/sdk/7.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1124,5): error NETSDK1151: The referenced project '../APSIM.Server/APSIM.Server.csproj' is a self-contained executable.  A self-contained executable cannot be referenced by a non self-contained executable.  For more information, see https://aka.ms/netsdk1151 [/tmp/ApsimX/ApsimNG/ApsimNG.csproj::TargetFramework=netcoreapp3.1]
```

The MacOS installer is showing this:
```
  ApsimNG -> /tmp/ApsimX/bin/Release/netcoreapp3.1/osx-x64/ApsimNG.dll
/usr/share/dotnet/sdk/7.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(112,5): error NETSDK1152: Found multiple publish output files with the same relative path: /tmp/ApsimX/Models/obj/Release/netcoreapp3.1/apphost, /tmp/ApsimX/Models/obj/Release/netcoreapp3.1/osx-x64/apphost, /tmp/ApsimX/bin/Release/netcoreapp3.1/Models.deps.json, /tmp/ApsimX/bin/Release/netcoreapp3.1/osx-x64/Models.deps.json, /tmp/ApsimX/bin/Release/netcoreapp3.1/Models.runtimeconfig.json, /tmp/ApsimX/bin/Release/netcoreapp3.1/osx-x64/Models.runtimeconfig.json. [/tmp/ApsimX/ApsimNG/ApsimNG.csproj::TargetFramework=netcoreapp3.1]
```
